# Generated by Django 4.2.23 on 2025-08-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shopped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
